// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231115100727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Data.Entities.AlbumEntity", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<uint>("Record")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumId");

                    b.ToTable("albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            Band = "Metallica",
                            Duration = new DateTime(2023, 11, 15, 1, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "...And Justice for All",
                            Record = 0u,
                            ReleaseDate = new DateTime(1988, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "1.Blackened 2. ...And Justice for All 3. Eye of the Beholder"
                        },
                        new
                        {
                            AlbumId = 2,
                            Band = "Metallica",
                            Duration = new DateTime(2023, 11, 15, 1, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "...And Justice for All",
                            Record = 0u,
                            ReleaseDate = new DateTime(1988, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "1.Blackened 2. ...And Justice for All 3. Eye of the Beholder"
                        },
                        new
                        {
                            AlbumId = 3,
                            Band = "Metallica",
                            Duration = new DateTime(2023, 11, 15, 1, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "...And Justice for All",
                            Record = 0u,
                            ReleaseDate = new DateTime(1988, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "1.Blackened 2. ...And Justice for All 3. Eye of the Beholder"
                        });
                });

            modelBuilder.Entity("Data.Entities.ContactEntity", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Birth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adam@wsei.pl",
                            Name = "Adam",
                            Phone = "354353637"
                        },
                        new
                        {
                            ContactId = 2,
                            Birth = new DateTime(2002, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jakubstr@gmail.com",
                            Name = "Jakub",
                            Phone = "123234345"
                        },
                        new
                        {
                            ContactId = 3,
                            Birth = new DateTime(1999, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cooldylan@gmail.com",
                            Name = "Dylan",
                            Phone = "456567678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
